

import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

export const getCategories = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db.query("categories").collect();
  },
});

export const initializeCategories = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if categories already exist
    const existingCategories = await ctx.db.query("categories").collect();
    if (existingCategories.length > 0) {
      return; // Categories already initialized
    }
    
    const categories = [
      {
        name: "🍕 Eten & drinken",
        emoji: "🍕",
        words: [
          { word: "Pizza", hint: "Italiaans" },
          { word: "Sushi", hint: "Japans" },
          { word: "Friet", hint: "Gouden stokjes" },
          { word: "Cola", hint: "Bruisend zwart" },
          { word: "Chocolade", hint: "Zoet bruin" },
          { word: "Brood", hint: "Dagelijks basis" },
          { word: "Appel", hint: "Rood fruit" },
          { word: "Pannenkoek", hint: "Plat en rond" },
          { word: "Spaghetti", hint: "Lange draden" },
          { word: "Koffie", hint: "Zwarte energie" },
          { word: "Thee", hint: "Warme bladeren" },
          { word: "IJs", hint: "Koud dessert" },
          { word: "Bier", hint: "Gouden schuim" },
          { word: "Wijn", hint: "Druiven drank" },
          { word: "Hamburger", hint: "Tussen broodjes" },
          { word: "Salade", hint: "Groene mix" },
          { word: "Tomaat", hint: "Rode bol" },
          { word: "Kaassoufflé", hint: "Gesmolten geel" },
          { word: "Rijst", hint: "Witte korrels" },
          { word: "Noodles", hint: "Aziatische draden" },
          { word: "Taco", hint: "Mexicaanse wrap" },
          { word: "Banaan", hint: "Gele kromme" },
          { word: "Yoghurt", hint: "Zure melk" },
          { word: "Croissant", hint: "Franse hoorn" },
          { word: "Bitterbal", hint: "Nederlandse bol" },
          { word: "Smoothie", hint: "Dikke drank" },
          { word: "Soep", hint: "W
arme vloeistof" },
          { word: "Vis", hint: "Zwemt in zee" },
          { word: "Vlees", hint: "Van dieren" },
          { word: "Groente", hint: "Uit de grond" },
          { word: "Pasta", hint: "Italiaanse vormen" },
          { word: "Cake", hint: "Zoete taart" },
          { word: "Donut", hint: "Gat in midden" },
          { word: "Chips", hint: "Knapperige plakjes" },
          { word: "Limonade", hint: "Zure bubbels" },
          { word: "Pindakaas", hint: "Bruine pasta" },
          { word: "Mango", hint: "Tropisch oranje" },
          { word: "Biefstuk", hint: "Dik vlees" },
          { word: "Kaas", hint: "Gele blokken" },
          { word: "Wafel", hint: "Vierkante gaatjes" },
          { word: "Mayonaise", hint: "Witte saus" }
        ],
        isDefault: true,
      },
      {
        name: "🌍 Landen & steden",
        emoji: "🌍",
        words: [
          { word: "Nederland", hint: "Oranje land" },
          { word: "Tokyo", hint: "Japanse hoofdstad" },
          { word: "Parijs", hint: "Stad van liefde" },
          { word: "New York", hint: "Grote appel" },
          { word: "Berlijn", hint: "Duitse hoofdstad" },
          { word: "Rome", hint: "Eeuwige stad" },
          { word: "Londen", hint: "Big Ben stad" },
          { word: "Sydney", hint: "Opera huis" },
          { word: "Kaapstad", hint: "Zuid-Afrika" },
          { word: "Rio de Janeiro", hint: "Carnaval stad" },
          { word: "Moskou", hint: "Rode plein" },
          { word: "Beijing", hint: "Verboden stad" },
          { word: "Toronto", hint: "CN Tower" },
          { word: "Barcelona", hint: "Sagrada Familia" },
          { word: "Istanbul", hint: "Twee continenten" },
          { word: "Bangkok", hint: "Thaise hoofdstad" },
          { word: "Singapore", hint: "Stadstaat" },
          { word: "Los Angeles", hint: "Hollywood" },
          { word: "Amsterdam", hint: "Grachten stad" },
          { word: "Dubai", hint: "Woestijn wolkenkrabbers" },
          { word: "Madrid", hint: "Spaanse hoofdstad" },
          { w
ord: "Athene", hint: "Griekse goden" },
          { word: "Kopenhagen", hint: "Kleine zeemeermin" },
          { word: "Oslo", hint: "Noorse hoofdstad" },
          { word: "Stockholm", hint: "Zweedse eilanden" },
          { word: "Helsinki", hint: "Finse hoofdstad" },
          { word: "Warsaw", hint: "Poolse hoofdstad" },
          { word: "Prague", hint: "Gouden stad" },
          { word: "Budapest", hint: "Donau rivier" },
          { word: "Lisbon", hint: "Portugese heuvels" }
        ],
        isDefault: true,
      },
      {
        name: "⭐ Beroemdheden",
        emoji: "⭐",
        words: [
          { word: "Lionel Messi", hint: "Argentijnse voetballer" },
          { word: "Cristiano Ronaldo", hint: "Portugese voetballer" },
          { word: "Beyoncé", hint: "Queen B" },
          { word: "Taylor Swift", hint: "Country pop" },
          { word: "Brad Pitt", hint: "Hollywood acteur" },
          { word: "Angelina Jolie", hint: "Tomb Raider" },
          { word: "Tom Holland", hint: "Spider-Man" },
          { word: "Emma Watson", hint: "Hermione" },
          { word: "Dwayne Johnson", hint: "The Rock" },
          { word: "Adele", hint: "Britse zangeres" },
          { word: "Kanye West", hint: "Rapper producer" },
          { word: "Rihanna", hint: "Barbados zangeres" },
          { word: "Oprah Winfrey", hint: "Talk show koningin" },
          { word: "Leonardo DiCaprio", hint: "Titanic acteur" },
          { word: "Jennifer Aniston", hint: "Friends Rachel" },
          { word: "Shakira", hint: "Heupen liegen niet" },
          { word: "Drake", hint: "Canadese rapper" },
          { word: "Billie Eilish", hint: "Groene haar" },
          { word: "Chris Hemsworth", hint: "Thor" },
          { word: "Zendaya", hint: "Spider-Man MJ" },
          { word: "Will Smith", hint: "Fresh Prince" },
          { word: "Gal Gadot", hint: "Wonder Woman" },
          { word: "Robert Downey Jr.", hint: "Iron Man" },
          { word: "Scarlett Johansson", hint: "Black Widow" },
          { word: "Ed Sheeran",
 hint: "Roodharige zanger" },
          { word: "Ariana Grande", hint: "Hoge paardenstaart" },
          { word: "Kim Kardashian", hint: "Reality TV" },
          { word: "Justin Bieber", hint: "Baby zanger" },
          { word: "Selena Gomez", hint: "Disney ster" },
          { word: "Michael Jordan", hint: "Basketball legende" }
        ],
        isDefault: true,
      },
      {
        name: "🎮 Games & consoles",
        emoji: "🎮",
        words: [
          { word: "Minecraft", hint: "Blokjes wereld" },
          { word: "Fortnite", hint: "Battle royale" },
          { word: "Among Us", hint: "Ruimte verraad" },
          { word: "Roblox", hint: "Gebruiker games" },
          { word: "Mario", hint: "Rode loodgieter" },
          { word: "Zelda", hint: "Prinsessen avontuur" },
          { word: "Playstation", hint: "Sony console" },
          { word: "Xbox", hint: "Microsoft console" },
          { word: "Nintendo Switch", hint: "Draagbare console" },
          { word: "Pac-Man", hint: "Gele bol" },
          { word: "Call of Duty", hint: "Oorlog shooter" },
          { word: "League of Legends", hint: "MOBA spel" },
          { word: "Candy Crush", hint: "Snoepjes match" },
          { word: "GTA", hint: "Criminele stad" },
          { word: "PUBG", hint: "Kip diner" },
          { word: "Overwatch", hint: "Hero shooter" },
          { word: "Tetris", hint: "Vallende blokken" },
          { word: "Pokémon", hint: "Vang ze allemaal" },
          { word: "Animal Crossing", hint: "Eiland leven" },
          { word: "Halo", hint: "Master Chief" },
          { word: "FIFA", hint: "Voetbal simulatie" },
          { word: "Mario Kart", hint: "Kart racen" },
          { word: "Super Smash Bros", hint: "Vecht platform" },
          { word: "The Sims", hint: "Leven simulatie" },
          { word: "Terraria", hint: "2D Minecraft" },
          { word: "Valorant", hint: "Tactische shooter" },
          { word: "Dota 2", hint: "Valve MOBA" },
          { word: "CS:GO", hint: "Counter terroristen" },
          { w
ord: "Apex Legends", hint: "Respawn royale" },
          { word: "Fall Guys", hint: "Jelly beans" }
        ],
        isDefault: true,
      },
      {
        name: "⚽ Sport & teams",
        emoji: "⚽",
        words: [
          { word: "Ajax", hint: "Amsterdamse club" },
          { word: "Barcelona", hint: "Catalaanse club" },
          { word: "Real Madrid", hint: "Koninklijke club" },
          { word: "Manchester United", hint: "Rode duivels" },
          { word: "NBA", hint: "Amerikaanse basketbal" },
          { word: "NFL", hint: "Amerikaanse voetbal" },
          { word: "Formula 1", hint: "Snelste auto's" },
          { word: "Tennis", hint: "Racket sport" },
          { word: "Rugby", hint: "Ovale bal" },
          { word: "Voetbal", hint: "Ronde bal" },
          { word: "Basketbal", hint: "Oranje bal" },
          { word: "Hockey", hint: "Stick sport" },
          { word: "Zwemmen", hint: "Water sport" },
          { word: "Skiën", hint: "Sneeuw sport" },
          { word: "Golf", hint: "Kleine witte bal" },
          { word: "Fietsen", hint: "Twee wielen" },
          { word: "Manchester City", hint: "Blauwe club" },
          { word: "Bayern München", hint: "Duitse reus" },
          { word: "Juventus", hint: "Oude dame" },
          { word: "PSG", hint: "Parijse club" },
          { word: "AC Milan", hint: "Rode zwarte" },
          { word: "Chelsea", hint: "Blauwe leeuw" },
          { word: "Liverpool", hint: "Rode vogels" },
          { word: "LA Lakers", hint: "Paarse goud" },
          { word: "Golden State Warriors", hint: "Bay Area" },
          { word: "Miami Heat", hint: "Florida vuur" },
          { word: "Chicago Bulls", hint: "Rode stier" },
          { word: "Dallas Cowboys", hint: "Amerikaanse cowboys" },
          { word: "PSV", hint: "Eindhovense club" },
          { word: "Feyenoord", hint: "Rotterdamse club" }
        ],
        isDefault: true,
      },
      {
        name: "🎬 Films & series",
        emoji: "🎬",
        words: [
          { word: "Avengers", hi
nt: "Marvel helden" },
          { word: "Friends", hint: "Zes vrienden" },
          { word: "Frozen", hint: "Laat het gaan" },
          { word: "Harry Potter", hint: "Tovenaar jongen" },
          { word: "The Batman", hint: "Donkere ridder" },
          { word: "Star Wars", hint: "Ruimte saga" },
          { word: "Stranger Things", hint: "Ondersteboven" },
          { word: "Breaking Bad", hint: "Meth leraar" },
          { word: "Game of Thrones", hint: "IJzeren troon" },
          { word: "Inception", hint: "Droom in droom" },
          { word: "Spider-Man", hint: "Web slingeren" },
          { word: "The Lion King", hint: "Hakuna Matata" },
          { word: "Toy Story", hint: "Speelgoed leven" },
          { word: "The Simpsons", hint: "Gele familie" },
          { word: "Shrek", hint: "Groene ogre" },
          { word: "Jumanji", hint: "Jungle spel" },
          { word: "Jurassic Park", hint: "Dinosaurus eiland" },
          { word: "Avatar", hint: "Blauwe aliens" },
          { word: "Black Panther", hint: "Wakanda koning" },
          { word: "Iron Man", hint: "Metalen pak" },
          { word: "Thor", hint: "Donder god" },
          { word: "Captain America", hint: "Schild held" },
          { word: "The Matrix", hint: "Rode pil" },
          { word: "The Dark Knight", hint: "Joker chaos" },
          { word: "Interstellar", hint: "Ruimte tijd" },
          { word: "The Godfather", hint: "Maffia familie" },
          { word: "Pulp Fiction", hint: "Tarantino verhalen" },
          { word: "Forrest Gump", hint: "Chocolade doos" },
          { word: "Titanic", hint: "Zinkend schip" },
          { word: "The Witcher", hint: "Monster jager" }
        ],
        isDefault: true,
      },
      {
        name: "🐶 Dieren",
        emoji: "🐶",
        words: [
          { word: "Hond", hint: "Beste vriend" },
          { word: "Kat", hint: "Miauwt veel" },
          { word: "Olifant", hint: "Grote oren" },
          { word: "Leeuw", hint: "Koning jungle" },
          { word: "Tijger", hint: "Gestreepte 
kat" },
          { word: "Beer", hint: "Honing liefhebber" },
          { word: "Aap", hint: "Bananen eter" },
          { word: "Paard", hint: "Galopperen" },
          { word: "Koe", hint: "Melk gever" },
          { word: "Schaap", hint: "Wol drager" },
          { word: "Varken", hint: "Modder rollen" },
          { word: "Kip", hint: "Eieren leggen" },
          { word: "Konijn", hint: "Lange oren" },
          { word: "Dolfijn", hint: "Slimme zwemmer" },
          { word: "Haai", hint: "Scherpe tanden" },
          { word: "Slang", hint: "Geen poten" },
          { word: "Kikker", hint: "Groene springer" },
          { word: "Vlinder", hint: "Kleurrijke vleugels" },
          { word: "Adelaar", hint: "Scherpe ogen" },
          { word: "Pinguïn", hint: "Zwart wit" },
          { word: "Egel", hint: "Stekelige bal" },
          { word: "Vos", hint: "Slimme roodharige" },
          { word: "Wolf", hint: "Roedel jager" },
          { word: "Uil", hint: "Nacht jager" },
          { word: "Eekhoorn", hint: "Noten verzamelaar" },
          { word: "Zebra", hint: "Gestreept paard" },
          { word: "Giraf", hint: "Lange nek" },
          { word: "Kangoeroe", hint: "Springende zak" },
          { word: "Koala", hint: "Eucalyptus eter" },
          { word: "Schildpad", hint: "Langzame schild" }
        ],
        isDefault: true,
      },
      {
        name: "📱 Objecten",
        emoji: "📱",
        words: [
          { word: "Telefoon", hint: "Bellen apparaat" },
          { word: "Laptop", hint: "Draagbare computer" },
          { word: "Stoel", hint: "Zitten meubel" },
          { word: "Tafel", hint: "Platte oppervlak" },
          { word: "Boek", hint: "Pagina's verhaal" },
          { word: "Pen", hint: "Schrijf gereedschap" },
          { word: "Auto", hint: "Vier wielen" },
          { word: "Fiets", hint: "Twee wielen" },
          { word: "Sleutel", hint: "Deur opener" },
          { word: "Portemonnee", hint: "Geld houder" },
          { word: "Bril", hint: "Ogen helper" },
          { word: 
"Hoed", hint: "Hoofd bedekking" },
          { word: "Tas", hint: "Spullen drager" },
          { word: "Lamp", hint: "Licht gever" },
          { word: "Deur", hint: "Kamer ingang" },
          { word: "Raam", hint: "Doorzichtige muur" },
          { word: "Fles", hint: "Vloeistof houder" },
          { word: "Beker", hint: "Drink container" },
          { word: "Camera", hint: "Foto maker" },
          { word: "Oordopjes", hint: "Oor geluid" },
          { word: "Monitor", hint: "Computer scherm" },
          { word: "Keyboard", hint: "Type toetsen" },
          { word: "Muis", hint: "Computer klikker" },
          { word: "Kast", hint: "Opslag meubel" },
          { word: "Kussen", hint: "Zacht hoofd" },
          { word: "Dekbed", hint: "Warm bedekking" },
          { word: "Vaas", hint: "Bloemen houder" },
          { word: "Schaar", hint: "Knip gereedschap" },
          { word: "Hamer", hint: "Sla gereedschap" },
          { word: "Horloge", hint: "Tijd teller" }
        ],
        isDefault: true,
      }
    ];
    
    for (const category of categories) {
      await ctx.db.insert("categories", category);
    }
  },
});
